# Generated by Django 3.2 on 2022-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
